require 'Items/SuburbsDistributions'
require 'Items/ProceduralDistributions'
require 'Vehicles/VehicleDistributions'

table.insert(VehicleDistributions["GloveBox"].items, "SWeapons.WeaponMag6");
table.insert(VehicleDistributions["GloveBox"].items, 0.0001);
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 0.0001);
table.insert(ProceduralDistributions["list"]["PlankStashMagazine"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["PlankStashMagazine"].items, 30);
table.insert(ProceduralDistributions["list"]["OfficeDeskHome"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["OfficeDeskHome"].items, 0.0);
table.insert(ProceduralDistributions["list"]["SchoolLockers"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["SchoolLockers"].items, 0.0);
table.insert(ProceduralDistributions["list"]["Locker"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["Locker"].items, 0.0);
table.insert(ProceduralDistributions["list"]["CrateMagazines"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["CrateMagazines"].items, 0.0025);
table.insert(ProceduralDistributions["list"]["DeskGeneric"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["DeskGeneric"].items, 0.0);
table.insert(ProceduralDistributions["list"]["ClassroomDesk"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["ClassroomDesk"].items, 0.0);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.0025);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.0025);
table.insert(ProceduralDistributions["list"]["ToolStoreBooks"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["ToolStoreBooks"].items, 0.0025);
table.insert(SuburbsDistributions["all"]["sidetable"].items, "SWeapons.WeaponMag6");
table.insert(SuburbsDistributions["all"]["sidetable"].items, 0.0);
table.insert(SuburbsDistributions["all"]["postbox"].items, "SWeapons.WeaponMag6");
table.insert(SuburbsDistributions["all"]["postbox"].items, 0.0025);
table.insert(ProceduralDistributions["list"]["BookstoreBooks"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["BookstoreBooks"].items, 0.0025);
table.insert(ProceduralDistributions["list"]["LibraryBooks"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["LibraryBooks"].items, 0.0025);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.0);
table.insert(ProceduralDistributions["list"]["GarageMetalwork"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["GarageMetalwork"].items, 0.0);
table.insert(ProceduralDistributions["list"]["CrateMagazines"].items, "SWeapons.WeaponMag6");
table.insert(ProceduralDistributions["list"]["CrateMagazines"].items, 0.0025);
table.insert(SuburbsDistributions["all"]["bin"].items, "SWeapons.WeaponMag6");
table.insert(SuburbsDistributions["all"]["bin"].items, 0.005);